# This script is designed to go through the process of checking the your top level VHDL file and constraints file against your scematic netlist.

# importing os module
import os

# setup the project settings
filename = "CHECK_PIN"
tld = "smartview4k_g3.vhd"#sys.argv[1]
netlist_filename = 'BMDPCB1120B_NETLIST.txt' #sys.argv[2] 
chip_id = 'U12' #sys.argv[3]  #this si the symbol in the scematic for the FPGA ic ----!!!! NOTE: make sure that this has a captial leter designator (eg: U17)
# prefix = "pl" # this is the prefix that sits in front of your pin names if that is how your scematic is layed out
print("******** Checking for changes in FPGA schematic pins ********")

# read the scematic file and make a VHDL file with ports matching the PLI,PLO,PLIO,PADI,PADO,PADIO net name
os.system(f"python make_tld_from_sch_2.py {filename} {netlist_filename} {chip_id}")

# make a constraints file from this top level VHDL file with XXX for all of the pin locations (for now)
os.system(f"python make_xdc.py {filename} {filename}_gen.vhd ")

# get the pin names and locations from the scematic file and apply them to the contraints file
os.system(f"python get_sch_loc.py {filename}.xdc {netlist_filename} {chip_id}")

# Replace the pin locations in the file generated by make_xdc with the locatiosn found in get_sch_loc.py
os.system(f"python replace_sch_pins.py {filename}.xdc matched_pins_with_sch.xdc XXX")


print("******** Comparing generated CHECK_PIN.XDC with TOP LEVEL VHDL ********")
# check, to be sure the pin matches between NETLIST AND CONTRSINTS file
# os.system(f"python check_sch.py matched_pins_with_sch.xdc {netlist_filename}") ## THIS IS BROKEN AT THE MOMENT???
# check, to be sure the pin/ports matche between VHDL AND CONTRSINTS file
os.system(f"python check_xdc.py {filename}.xdc {tld}")


print("")
print("Removing temporary files...")
if os.path.exists("matched_pins_with_sch.xdc"):
  os.remove("matched_pins_with_sch.xdc")
else:
  print("Error removing temp files!")
if os.path.exists("CHECK_PIN.xdc"):
  os.remove("CHECK_PIN.xdc")
else:
  print("Error removing temp files!")
if os.path.exists("CHECK_PIN_gen.vhd"):
  os.remove("CHECK_PIN_gen.vhd")
else:
  print("Error removing temp files!")

print("Finished")
